language: java
install: true

#script:
#  - git clone https://github.com/gradle/gradle-site-plugin.git
#  - cd gradle-site-plugin
#  - ./gradlew build

script:
  - ./gradlew build -x signArchives -s

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/modules-2/
    - $HOME/.gradle/wrapper/dists/
